# Generated by Django 3.1.3 on 2020-11-26 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/'), size=None)),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('stories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
