# Generated by Django 3.1.3 on 2020-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
